spring:
  # настройка подключения к PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # настройка JPA и hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # настройка кэша (redis)
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  # настройка flyway (управление миграциями)
  flyway:
    enabled: true
    baseline-on-migrate: true

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
